version: '3'

services:
  web:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    environment:
      - PHP_ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=client_host=host.docker.internal
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
